springdoc:
  # Swagger? ??? ?? API? ??? ??? ??
  packages-to-scan: com.kang.restapi

  # consumes : Swagger? ????? ???? "??"? "Content-Type"? ??
  # produces : Swagger? ????? ???? "??" ? "Content-Type"? ??
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8