spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/cqrs
    username: swcamp
    password: swcamp

image:
  image-dir: /Users/gangseonghun/desktop
  image-url: http://localhost:8080/productimgs/
